version: '3.7'
services:
  database:
    image: postgres:16
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/

  # backend:
  #   image: golang:1.21.3-alpine3.18
  #   container_name: backend
  #   working_dir: /app
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - .:/app
  #   ports:
  #     - '8080:8080'
  #   command: ['go', 'run', 'server.go']
